---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth
      workload.auth.cattle.io/workloadselector: statefulSet-openim-auth
  serviceName: auth
  template:
    metadata:
      labels:
        app: auth
        workload.auth.cattle.io/workloadselector: statefulSet-openim-auth
    spec:
      containers:
        - image: "IMAGE_TAG"
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          ports:
          - name: p10600
            protocol: TCP
            containerPort: 10600
          imagePullPolicy: Always
          name: auth
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /Open-IM-Server/config.tmp.yaml
              name: vol2
              readOnly: true
              subPath: config.yaml
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 256
            name: config.yaml
            optional: false
          name: vol2
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - name: p10600
      port: 10600
      protocol: TCP
      targetPort: 10600
  selector:
    app: auth
  type: ClusterIP
