---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: push

spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: push
      workload.user.cattle.io/workloadselector: statefulSet-openim-push
  serviceName: push
  template:
    metadata:
      labels:
        app: push
        workload.user.cattle.io/workloadselector: statefulSet-openim-push
    spec:
      containers:
        - image: "IMAGE_TAG"
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          ports:
          - name: p10700
            protocol: TCP
            containerPort: 10700
          imagePullPolicy: Always
          name: push
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /Open-IM-Server/config.tmp.yaml
              name: vol2
              readOnly: true
              subPath: config.yaml
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 256
            name: config.yaml
            optional: false
          name: vol2
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: push

spec:
  ports:
    - name: p10700
      port: 10700
      protocol: TCP
      targetPort: 10700
  selector:
    app: push
  type: ClusterIP
